[package]
name = "exploited-vulns-feed"
version = "0.3.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cfg-if = "0.1.2"
worker = "0.0.9"
serde = "1.0.137"
serde_json = "1.0.67"
rss = "1.10.0"