name = "exploited-vulns-feed"
type = 'javascript'
account_id = ""
zone_id = ""
workers_dev = true
compatibility_date = "2022-01-20"

[vars]
WORKERS_RS_VERSION = "0.0.9"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"
[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
